const candidates=[
 {name:'周子涵',role:'产品实习生 · 上海',initial:'周',score:92,status:'强匹配',tone:'green',school:'复旦大学 · 信息管理',skills:'SQL  ·  用户研究  ·  B端产品'},
 {name:'陈思远',role:'产品经理 · 北京',initial:'陈',score:86,status:'待复核',tone:'amber',school:'浙江大学 · 工业设计',skills:'Axure  ·  数据分析  ·  项目管理'},
 {name:'林嘉怡',role:'运营实习生 · 深圳',initial:'林',score:78,status:'待复核',tone:'amber',school:'中山大学 · 新闻传播',skills:'内容运营  ·  社群增长  ·  Excel'}
];
const viewData={
 candidates:{eyebrow:'PIPELINE / 01',title:'候选人筛选',sub:'产品实习生 · 2024 秋招批次'},
 jd:{eyebrow:'ROLE SETUP / 02',title:'岗位与 JD',sub:'让 AI 把一份 JD 变成可执行的筛选标准'},
 interview:{eyebrow:'INTERVIEW KIT / 03',title:'面试题库',sub:'围绕岗位能力模型，自动生成结构化追问'},
 reviews:{eyebrow:'DECISION / 04',title:'面试评价',sub:'把面试记录沉淀为统一、可比较的决策依据'}
};
function candidateHTML(){return `<div class="stats"><div class="stat"><span>已分析简历</span><strong>12</strong><em>+4 本周</em></div><div class="stat"><span>强匹配候选人</span><strong>4</strong><em>33.3%</em></div><div class="stat"><span>平均匹配度</span><strong>81%</strong><em>+6.2%</em></div><div class="stat"><span>待处理任务</span><strong>7</strong><em class="warn">需要关注</em></div></div><div class="content-grid"><section class="panel"><div class="panel-head"><h2>候选人列表</h2><span>按匹配度排序 · 共 12 人</span></div><div class="toolbar"><div class="search"><input id="searchInput" placeholder="搜索姓名、学校或技能..." /></div><select class="filter" id="statusFilter"><option>全部状态</option><option>强匹配</option><option>待复核</option></select><button class="filter" id="exportBtn">导出</button></div><div class="candidate-list" id="candidateList"></div></section><aside class="panel side-panel"><div class="panel-head"><h2>当前岗位</h2><span>JD 已解析</span></div><div class="role-block"><div class="role-top"><strong>产品实习生</strong><b>匹配 81%</b></div><div class="role-sub">上海 · 互联网产品部 · 实习</div><div class="chips"><i>用户研究</i><i>数据分析</i><i>B端产品</i></div></div><div class="requirements"><h3>AI 提炼的任职要求</h3><p>✓　本科及以上，理工科 / 商科背景优先</p><p>✓　具备用户调研、需求分析或产品实习经验</p><p>✓　熟悉 SQL，能独立完成基础数据分析</p><p>✓　每周到岗 4 天，连续实习 3 个月</p></div><div class="insight"><h3>AI 招聘洞察</h3><p>目前有 <strong>4 位候选人</strong>满足全部硬性要求。建议优先推进周子涵，并在面试中重点验证其 <strong>数据驱动的产品判断</strong>。</p></div></aside></div>`}
function pageHTML(view){if(view==='candidates')return candidateHTML();if(view==='jd')return `<div class="two-col"><section class="panel section-panel"><h2>产品实习生 · JD 原文</h2><p>粘贴岗位描述，AI 将自动识别硬性要求与加分项。</p><textarea class="text-area" id="jdText">我们正在寻找一名产品实习生，协助完成用户研究、需求分析与产品迭代。要求本科及以上学历，熟悉 SQL 或其他数据分析工具，有互联网产品实习经验，每周到岗 4 天，连续实习 3 个月。</textarea><button class="primary" id="parseBtn">✦ 重新解析 JD</button></section><section class="panel section-panel"><h2>结构化筛选标准</h2><p>AI 已从 JD 中提取 4 项硬性要求与 3 项加分项。</p><div class="requirement-list"><div>学历背景 <span>本科及以上 · 硬性</span></div><div>产品相关经验 <span>有实习经验 · 硬性</span></div><div>数据分析能力 <span>SQL · 硬性</span></div><div>到岗稳定性 <span>4天/周 · 硬性</span></div><div>加分项 <span>B端 / 用户研究 / 竞品分析</span></div></div></section></div>`;if(view==='interview')return `<section class="panel section-panel"><div class="section-title"><div><h2>产品实习生 · 一面题库</h2><p>共 8 题 · 已按能力维度分组 · STAR 追问已生成</p></div><button class="primary" id="generateBtn">✦ 生成新题</button></div>${[['01 / 用户洞察','请分享一个你通过用户反馈，推动产品或方案改进的经历。','当时的具体情境是什么？你负责哪一部分？你采取了哪些行动？最终用什么指标证明结果？'],['02 / 数据分析','在一个你熟悉的项目中，你如何使用数据发现问题并做出判断？','你选择了哪些数据？有没有遇到数据与直觉冲突的时刻？最后的结论如何影响决策？'],['03 / 产品思维','如果让你优化校园二手交易平台，你会从哪里开始？','你如何定义核心用户？第一步会验证什么假设？如果资源有限，你会放弃什么？']].map(q=>`<div class="question"><label>${q[0]}</label><strong>${q[1]}</strong><p><b>STAR 追问：</b>${q[2]}</p></div>`).join('')}</section>`;return `<section class="panel section-panel"><div class="section-title"><div><h2>周子涵 · 一面评价</h2><p>面试官：林晓雯 · 2024-06-20 14:00</p></div><span class="tag green">已完成</span></div><table class="review-table"><thead><tr><th>评价维度</th><th>面试记录摘要</th><th>评分</th></tr></thead><tbody><tr><td>用户洞察</td><td>能清晰描述校园项目中的访谈过程，主动归纳用户痛点。</td><td>★★★★☆</td></tr><tr><td>数据分析</td><td>掌握 SQL 基础，能用漏斗定位问题，但指标体系经验有限。</td><td>★★★☆☆</td></tr><tr><td>结构化思考</td><td>回答有框架，能区分现象与原因，追问下仍保持逻辑。</td><td>★★★★☆</td></tr><tr><td>沟通协作</td><td>表达自然，能说明与研发协作时的分歧和解决方式。</td><td>★★★★☆</td></tr></tbody></table><div class="recommend"><div><strong>建议：进入下一轮</strong><small>综合评分 4.0 / 5 · 建议重点追问数据指标设计</small></div><button class="primary" id="saveReview">保存评价</button></div></section>`}
function render(view='candidates'){const d=viewData[view];document.getElementById('crumbTitle').textContent=d.title;document.getElementById('appContent').innerHTML=`<div class="view ${view==='candidates'?'':'view-'+view}"><div class="view-head"><div><p class="eyebrow">${d.eyebrow}</p><h1>${d.title}</h1><p class="view-sub">${d.sub}</p></div>${view==='candidates'?'<button class="primary" id="uploadBtn">＋ 导入简历</button>':''}</div>${pageHTML(view)}</div>`;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='candidates')bindCandidates();bindActions()}
function bindCandidates(){const list=document.getElementById('candidateList');const draw=()=>{const term=document.getElementById('searchInput').value.toLowerCase(),filter=document.getElementById('statusFilter').value;list.innerHTML=candidates.filter(c=>(filter==='全部状态'||c.status===filter)&&[c.name,c.school,c.skills].join(' ').toLowerCase().includes(term)).map(c=>`<div class="candidate"><div class="candidate-avatar">${c.initial}</div><div class="candidate-info"><strong>${c.name}</strong><small>${c.role}</small><small>${c.school}　·　${c.skills}</small></div><div class="score-wrap"><div class="score ${c.score>88?'high':'mid'}">${c.score}%</div><div class="match-bar"><i style="width:${c.score}%"></i></div><small>匹配度</small></div><div class="candidate-status"><span class="tag ${c.tone}">${c.status}</span><small>近期更新</small></div></div>`).join('')||'<div class="empty">没有符合条件的候选人</div>'};draw();document.getElementById('searchInput').oninput=draw;document.getElementById('statusFilter').onchange=draw;document.getElementById('exportBtn').onclick=()=>toast('候选人清单已导出');document.getElementById('uploadBtn').onclick=()=>document.getElementById('resumeFiles').click();document.getElementById('resumeFiles').onchange=async(e)=>{const files=e.target.files;if(!files.length)return;const fd=new FormData();[...files].forEach(f=>fd.append('files',f));toast('正在解析 '+files.length+' 份简历...');try{const r=await fetch('/api/resumes/upload',{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.error);candidates.unshift(...data.candidates.map(c=>({name:c.name,role:'新导入候选人',initial:c.name.slice(0,1),score:c.score,status:c.status,tone:c.status==='强匹配'?'green':'amber',school:c.school,skills:c.skills.join(' · ')})));document.getElementById('searchInput').value='';document.getElementById('statusFilter').value='全部状态';bindCandidates();toast('已完成 '+data.count+' 份简历解析')}catch(err){toast('解析失败：'+err.message)}}}
function bindActions(){[['parseBtn','JD 解析完成，已更新筛选标准'],['generateBtn','已生成 3 道 STAR 追问题'],['saveReview','面试评价已保存']].forEach(([id,msg])=>{const el=document.getElementById(id);if(el)el.onclick=()=>toast(msg)})}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>render(btn.dataset.view));render();

